name: action-to-ecs
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  ECS_HOST: 18.181.146.129
# ECSにpingを送るサンプル
jobs:
  # 1. Batsのバージョンを確認するジョブ
  sample-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v

  # 2. ECSのヘルスチェックを行うジョブ
  ecs-refresh:
    runs-on: ubuntu-latest
    needs: sample-first-job
    steps:
      - name: Check ECS health
        run: |
          # ECSのヘルスチェックエンドポイントにアクセス
          curl -f http://$ECS_HOST/refresh || exit 1
          echo "Updated ECS successfully"

  # 3. ECSのヘルスチェックを行うジョブ（別のサンプル）
  ecs-health-check:
    runs-on: ubuntu-latest
    needs: ecs-refresh
    steps:
      - name: Check ECS health
        run: |
          # ECSのヘルスチェックエンドポイントにアクセス
          curl -f http://$ECS_HOST/list || exit 1
          echo "ECS is healthy"