name: action-to-ecs
run-name: ${{ github.actor }} is learning GitHub Actions
# on: [push]
env:
  ECS_HOST: 13.114.30.124
# ECSにpingを送るサンプル
jobs:
  # 0. Batsのバージョンを確認するジョブ
  sample-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v

  # 1. S3からデータを取得前のファイルの状態を確認
  ecs-check-list-before:
    runs-on: ubuntu-latest
    needs: sample-first-job
    steps:
      - name: Check List
        run: |
          # ECSのヘルスチェックエンドポイントにアクセス
          curl -f http://$ECS_HOST/list || exit 1
          echo "ECS is healthy"

  # 2. S3からデータを取得
  ecs-refresh:
    runs-on: ubuntu-latest
    needs: ecs-check-list-before
    steps:
      - name: Refresh ECS from S3
        run: |
          # ECSのヘルスチェックエンドポイントにアクセス
          curl -f http://$ECS_HOST/refresh || exit 1
          echo "Updated ECS successfully"

  # 3. S3からデータを取得したことを確認
  ecs-check-list-after:
    runs-on: ubuntu-latest
    needs: ecs-refresh
    steps:
      - name: Check List
        run: |
          # ECSのヘルスチェックエンドポイントにアクセス
          curl -f http://$ECS_HOST/list || exit 1
          echo "ECS is healthy"