name: Convert XML to JSON with xq

on:
  push:
  workflow_dispatch:

env:
  # $WORKSPACE
  WORKSPACE: "XML2JSON"
  INPUT_XML: "XML2JSON/input.xml"
  BASE_JSON: "XML2JSON/base.json"
  CONVERTED_JSON: "XML2JSON/converted.json"
  OUTPUT_JSON: "XML2JSON/output.json"
  
jobs:
  # 1. Checkout code and set up environment
  sample-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ls cmd
        run: ls
      - name: pwd cmd
        run: pwd
      
  # 2. Convert XML to JSON
  convert-xml-2-json:
    runs-on: ubuntu-latest
    needs: sample-first-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Output Env
        run: echo $WORKSPACE

      - name: Install xq (yq)
        run: pip install yq

      - name: Check jq version
        run: jq --version

      # 1. xq . < input.xml: XML を JSON に変換
      # 2. jq 'walk(...)': JSON ツリー全体を再帰的に探索し、
      # 3. 各 object から属性キー（@で始まるもの）を削除し、
      # 4. "#text" キーを持つ object はその値だけを抽出して置き換える処理
      - name: Convert XML to JSON using xq
        run: |
          xq . < $INPUT_XML | jq 'walk(
            if type == "object" then
              with_entries(select(.key | startswith("@") | not)) 
              | if has("#text") then .["#text"] else . end
            else .
            end
          )' > $CONVERTED_JSON

      - name: Show Result
        run: cat $CONVERTED_JSON

      # 次のジョブで使用するために、変換された JSON を保存
      - name: Save Converted JSON
        uses: actions/upload-artifact@v4
        with:
          name: my-converted-json
          path: ${{ env.CONVERTED_JSON }}

  # 3. Insert JSON into Origen Json
  insert-json:
    runs-on: ubuntu-latest
    needs: convert-xml-2-json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Converted JSON
        uses: actions/download-artifact@v4
        with:
          name: my-converted-json
          path: ${{ env.WORKSPACE }}

      - name: Merge converted JSON into environmentTests
        run: |
          jq --slurpfile newdata $CONVERTED_JSON '
            .soatestOptions.environmentConfig.environmentTests[0] = $newdata[0]
          ' $BASE_JSON > $OUTPUT_JSON

      - name: Show Output JSON
        run: cat $OUTPUT_JSON